---
- name: install curl and perl module on centos
  yum: name={{ item }} state=present
  with_items:
    - curl
    - perl-ExtUtils-MakeMaker

- name: install cpanm
  shell: curl -L http://cpanmin.us | perl - App::cpanminus
